const CLOUDINARY_CLOUD_NAME = "ravindramohith";
const CLOUDINARY_API_KEY = "342594479789283";
const CLOUDINARY_API_SECRET = "LpjrvJyRM3fmIG3BJb8bDmrL1V0";
const SMTP_HOST = "smtp.mailtrap.io";
const SMTP_PORT = "2525";
const SMTP_USER = "950bf894fdf581";
const SMTP_PASSWORD = "94fa99bf15125a";
const STRIPE_API_KEY =
  "pk_test_51MFjstSIdrJ0lrXXgnKt6vClK2wBnajndUdjcxPMkcx6D3t1AAeooBwpRuQ3jYy7AYOhKAyee6VuVKqvrLHwai2100iTGCDHkn";
const STRIPE_SECRET_KEY =
  "sk_test_51MFjstSIdrJ0lrXXZX5R7XwP5jd0dZicYS1UzAnYivAlRcfJsapFiDZRDvWCjQ6hmvUEj6RKsIJkO7E5BxFMLt04004PrI3gnG";
const STRIPE_WEBHOOK_SECRET =
  "whsec_nu88FkdBAljmlTmre4qu5kTU5CHO0odY";
module.exports = {
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  CLOUDINARY_CLOUD_NAME,
  SMTP_HOST,
  SMTP_PORT,
  SMTP_USER,
  SMTP_PASSWORD,
  STRIPE_API_KEY,
  STRIPE_SECRET_KEY,
  STRIPE_WEBHOOK_SECRET,
};
